name: Tests

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - moodle-branch: MOODLE_401_STABLE
            php: 8.1
          - moodle-branch: MOODLE_405_STABLE
            php: 8.2

    name: ${{ matrix.moodle-branch }}  php ${{ matrix.php }}

    steps:
      - name: checkout plugin
        uses: actions/checkout@v3
        with:
          path: this-plugin

      - name: setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, pgsql, mysqli, gd, xmlrpc, zip
          ini-values: max_input_vars=5000
          coverage: none

      - name: composer
        run: |
           composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^4
           echo $(cd ci/bin; pwd) >> $GITHUB_PATH

      - name: install moodle
        run: |
          mkdir -p moodle
          ci/bin/moodle-plugin-ci install --db-host=127.0.0.1 --plugin this-plugin
        env:
          DB: mysqli
          MUSTACHE_IGNORE_NAMES: 'mobile_service.mustache'

      - name: PHP Lint
        run: ci/bin/moodle-plugin-ci phplint this-plugin

      - name: PHP Copy/Paste Detector
        run: ci/bin/moodle-plugin-ci phpcpd this-plugin || true

      - name: PHP Mess Detector
        run: ci/bin/moodle-plugin-ci phpmd this-plugin

      - name: Moodle Code Checker
        run: ci/bin/moodle-plugin-ci codechecker this-plugin || true

      - name: Moodle PHPDoc Checker
        run: ci/bin/moodle-plugin-ci phpdoc this-plugin || true

      - name: Validating
        run: ci/bin/moodle-plugin-ci validate this-plugin

      - name: Check upgrade savepoints
        run: ci/bin/moodle-plugin-ci savepoints this-plugin

      - name: Mustache Lint
        run: ci/bin/moodle-plugin-ci mustache this-plugin || true

      - name: Grunt
        run: ci/bin/moodle-plugin-ci grunt this-plugin || true

      - name: PHPUnit tests
        run: ci/bin/moodle-plugin-ci phpunit --fail-on-warning this-plugin

      - name: Behat features
        run: ci/bin/moodle-plugin-ci behat --auto-rerun this-plugin || true